name: CI

# Trigger ONLY on push
on:
  push:

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Lint
        run: |
          npm run lint
      - name: Test
        run: |
          npm run test
      # Only publish for a tagged release on the master branch
      - name: Publish
        if: contains(github.ref, 'refs/tags/v')
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build --no-cache -t $DOCKER_USERNAME/editor-s3-bucket-importer:$GITHUB_SHA -t $DOCKER_USERNAME/editor-s3-bucket-importer:latest .
          docker push $DOCKER_USERNAME/editor-s3-bucket-importer
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
